version: '3'
services:
  server:
    image: server
    build: ../test_build
    ports:
      - '80:81'
  proxy:
    image: nginx
    ports:
      - '8080:80'
    volumes:
      - './default.conf:/etc/nginx/conf.d/default.conf'

